[package]
name = "integer-encoding"
version = "0.1.0"
authors = ["Lewin Bormann <lbo@spheniscida.de>"]
description = "Trait-based encoding/decoding of integers into/from varint+zigzag/fixedint representation"

[dependencies]
